### ISSUE TITLE
Refused to execute script from 'https://raw.github.com/...'

### ISSUE THREAD

**Issue by cauburtin** [Zirak/SO-ChatBot#224] opened 2015-01-31 20:43 UTC
Hi,
When I execute the bookmarlet, on Chrome, in the console I see this error.

> Refused to execute script from 'https://raw.github.com/Zirak/SO-ChatBot/master/master.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

This issue is explained here https://code.google.com/p/chromium/issues/detail?id=180007#c11 
Replacing all *raw.github.com* with *rawgit.com* could make it work

When I change the url in bookmarklet with rawgit.com, it goes further until another raw.github.com:

> Refused to execute script from 'https://raw.github.com/jashkenas/coffee-script/master/extras/coffee-script.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by SomeKittens** [comment] 2015-02-02 19:56
This is fixed by PRs #221 #222 #223, closing as dupe of those.

**Closed by SomeKittens** 2015-02-02 19:56 UTC

**Comment by cauburtin** [comment] 2015-02-03 00:49
thanks
